{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "af1bdc67-3e2b-47f5-91e8-e4867aadb7c4",
   "metadata": {},
   "outputs": [],
   "source": [
    "from fastapi import FastAPI, HTTPException\n",
    "from fastapi.middleware.cors import CORSMiddleware\n",
    "from pydantic import BaseModel\n",
    "import joblib\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "app = FastAPI(title=\"CommodityIQ API\")\n",
    "\n",
    "app.add_middleware(\n",
    "    CORSMiddleware,\n",
    "    allow_origins=['*'],\n",
    "    allow_methods=['*'],\n",
    "    allow_headers=['*']\n",
    ")\n",
    "\n",
    "models = {\n",
    "    'gold': joblib.load('gold_xgb_model.pkl'),\n",
    "    'platinum': joblib.load('platinum_xgb_model.pkl'),\n",
    "    'oil': joblib.load('oil_xgb_model.pkl'),\n",
    "    'copper': joblib.load('copper_xgb_model.pkl'),\n",
    "}\n",
    "\n",
    "commodity_info = {\n",
    "    'gold': {'name': 'Gold', 'unit': 'oz', 'currency': 'USD'},\n",
    "    'platinum': {'name': 'Platinum', 'unit': 'oz', 'currency': 'USD'},\n",
    "    'oil': {'name': 'Crude Oil', 'unit': 'barrel', 'currency': 'USD'},\n",
    "    'copper': {'name': 'Copper', 'unit': 'lb', 'currency': 'USD'},\n",
    "}\n",
    "\n",
    "class PredictionRequest(BaseModel):\n",
    "    commodity: str\n",
    "    forecast_days: int = 30\n",
    "\n",
    "class PredictionResponse(BaseModel):\n",
    "    commodity: str\n",
    "    current_price: float\n",
    "    current_date: str\n",
    "    forecast_date: str\n",
    "    predicted_price: float\n",
    "    change_amount: float\n",
    "    change_percent: float\n",
    "    signal: str\n",
    "    confidence: float\n",
    "    recommendations: list\n",
    "\n",
    "class DashboardResponse(BaseModel):\n",
    "    commodities: list\n",
    "\n",
    "def get_current_price(commodity: str) -> float:\n",
    "    sample_prices = {\n",
    "        'gold': 3000,\n",
    "        'platinum': 980,\n",
    "        'oil': 85.50,\n",
    "        'copper': 4.50\n",
    "    }\n",
    "    return sample_prices.get(commodity, 0)\n",
    "\n",
    "def get_latest_features(commodity: str) -> pd.DataFrame:\n",
    "    if commodity == 'gold':\n",
    "        features = pd.DataFrame({\n",
    "            'gold_price': [3000],\n",
    "            'gold_ma_7': [2980],\n",
    "            'gold_ma_30': [2950],\n",
    "            'gold_ma_200': [2800],\n",
    "            'gold_volatility': [50],\n",
    "            'gold_roc': [0.02],\n",
    "            'usd_zar': [18.5],\n",
    "            'usd_zar_ma_30': [18.3],\n",
    "            'usd_zar_change': [0.01],\n",
    "            'rsi': [62],\n",
    "            'month': [datetime.now().month],\n",
    "            'quarter': [datetime.now().quarter]\n",
    "        })\n",
    "    elif commodity == 'platinum':\n",
    "        features = pd.DataFrame({\n",
    "            'platinum_price': [980],\n",
    "            'platinum_ma_7': [975],\n",
    "            'platinum_ma_30': [965],\n",
    "            'platinum_ma_200': [940],\n",
    "            'platinum_volatility': [20],\n",
    "            'platinum_roc': [0.015],\n",
    "            'usd_zar': [18.5],\n",
    "            'usd_zar_ma_30': [18.3],\n",
    "            'usd_zar_change': [0.01],\n",
    "            'rsi': [55],\n",
    "            'month': [datetime.now().month],\n",
    "            'quarter': [datetime.now().quarter]\n",
    "        })\n",
    "    elif commodity == 'oil':\n",
    "        features = pd.DataFrame({\n",
    "            'oil_price': [85.50],\n",
    "            'oil_ma_7': [85.00],\n",
    "            'oil_ma_30': [84.50],\n",
    "            'oil_ma_200': [82.00],\n",
    "            'oil_volatility': [5.2],\n",
    "            'oil_roc': [0.015],\n",
    "            'usd_zar': [18.5],\n",
    "            'usd_zar_ma_30': [18.3],\n",
    "            'usd_zar_change': [0.005],\n",
    "            'rsi': [58],\n",
    "            'month': [datetime.now().month],\n",
    "            'quarter': [datetime.now().quarter]\n",
    "        })\n",
    "    elif commodity == 'copper':\n",
    "        features = pd.DataFrame({\n",
    "            'copper_price': [4.50],\n",
    "            'copper_ma_7': [4.48],\n",
    "            'copper_ma_30': [4.42],\n",
    "            'copper_ma_200': [4.20],\n",
    "            'copper_volatility': [0.15],\n",
    "            'copper_roc': [0.012],\n",
    "            'usd_zar': [18.5],\n",
    "            'usd_zar_ma_30': [18.3],\n",
    "            'usd_zar_change': [0.01],\n",
    "            'rsi': [60],\n",
    "            'month': [datetime.now().month],\n",
    "            'quarter': [datetime.now().quarter]\n",
    "        })\n",
    "    return features\n",
    "\n",
    "def generate_signal(change_percent: float) -> str:\n",
    "    if change_percent > 5:\n",
    "        return \"STRONG BUY\"\n",
    "    elif change_percent > 2:\n",
    "        return \"BUY\"\n",
    "    elif change_percent < -5:\n",
    "        return \"STRONG SELL\"\n",
    "    elif change_percent < -2:\n",
    "        return \"SELL\"\n",
    "    else:\n",
    "        return \"HOLD\"\n",
    "\n",
    "def generate_recommendations(commodity: str, signal: str, change_percent: float) -> list:\n",
    "    if commodity in ['gold', 'platinum']:\n",
    "        if signal in ['BUY', 'STRONG BUY']:\n",
    "            return [\n",
    "                \"Increase production immediately\",\n",
    "                f\"Expect {abs(change_percent):.1f}% price increase\",\n",
    "                \"Consider stockpiling refined metal\",\n",
    "                \"Hedge 50% of next quarter production\"\n",
    "            ]\n",
    "        elif signal in ['SELL', 'STRONG SELL']:\n",
    "            return [\n",
    "                \"Sell current stockpile NOW\",\n",
    "                f\"Prices may drop {abs(change_percent):.1f}%\",\n",
    "                \"Reduce production temporarily\",\n",
    "                \"Wait for market recovery\"\n",
    "            ]\n",
    "        else:\n",
    "            return [\n",
    "                \"Maintain current production levels\",\n",
    "                \"Market is stable - no urgent action\",\n",
    "                \"Monitor closely for changes\"\n",
    "            ]\n",
    "    elif commodity == 'oil':\n",
    "        if signal in ['BUY', 'STRONG BUY']:\n",
    "            return [\n",
    "                \"HEDGE fuel costs immediately!\",\n",
    "                f\"Oil may rise {abs(change_percent):.1f}%\",\n",
    "                \"Lock in current fuel contracts\",\n",
    "                \"Consider passing costs to customers\"\n",
    "            ]\n",
    "        elif signal in ['SELL', 'STRONG SELL']:\n",
    "            return [\n",
    "                \"DO NOT HEDGE - wait for lower prices\",\n",
    "                f\"Oil costs may drop {abs(change_percent):.1f}%\",\n",
    "                \"Delay large fuel purchases\",\n",
    "                \"Use spot market instead of contracts\"\n",
    "            ]\n",
    "        else:\n",
    "            return [\n",
    "                \"Normal purchasing patterns\",\n",
    "                \"Oil prices stable\",\n",
    "                \"No urgent hedging needed\"\n",
    "            ]\n",
    "    elif commodity == 'copper':\n",
    "        if signal in ['BUY', 'STRONG BUY']:\n",
    "            return [\n",
    "                \"Purchase copper NOW before price rise\",\n",
    "                f\"Prices rising {abs(change_percent):.1f}%\",\n",
    "                \"Lock in 6-month supply contracts\",\n",
    "                \"Start copper-intensive projects earlier\"\n",
    "            ]\n",
    "        elif signal in ['SELL', 'STRONG SELL']:\n",
    "            return [\n",
    "                \"WAIT to purchase copper\",\n",
    "                f\"Prices dropping {abs(change_percent):.1f}%\",\n",
    "                \"Delay non-urgent purchases\",\n",
    "                \"Negotiate lower prices with suppliers\"\n",
    "            ]\n",
    "        else:\n",
    "            return [\n",
    "                \"Normal purchasing patterns\",\n",
    "                \"Copper prices stable\",\n",
    "                \"No urgency\"\n",
    "            ]\n",
    "    return []\n",
    "\n",
    "@app.get('/')\n",
    "def home():\n",
    "    return {\n",
    "        'name': 'CommodityIQ API',\n",
    "        'version': '1.0.0',\n",
    "        'status': 'running',\n",
    "        'available_commodities': list(models.keys())\n",
    "    }\n",
    "\n",
    "@app.get('/commodities')\n",
    "def list_commodities():\n",
    "    return {\n",
    "        'commodities': [\n",
    "            {'id': key, 'name': info['name'], 'unit': info['unit'], 'currency': info['currency']}\n",
    "            for key, info in commodity_info.items()\n",
    "        ]\n",
    "    }\n",
    "\n",
    "@app.post('/predict', response_model=PredictionResponse)\n",
    "def predict(request: PredictionRequest):\n",
    "    if request.commodity not in models:\n",
    "        raise HTTPException(status_code=400, detail=f\"Commodity '{request.commodity}' not supported.\")\n",
    "    if request.forecast_days not in [7, 30, 60, 90]:\n",
    "        raise HTTPException(status_code=400, detail=\"forecast_days must be 7, 30, 60, or 90\")\n",
    "\n",
    "    current_price = get_current_price(request.commodity)\n",
    "    features = get_latest_features(request.commodity)\n",
    "    predicted_price = models[request.commodity].predict(features)[0]\n",
    "\n",
    "    if request.forecast_days == 7:\n",
    "        predicted_price = current_price + (predicted_price - current_price) * 0.25\n",
    "    elif request.forecast_days == 60:\n",
    "        predicted_price = current_price + (predicted_price - current_price) * 1.8\n",
    "    elif request.forecast_days == 90:\n",
    "        predicted_price = current_price + (predicted_price - current_price) * 2.5\n",
    "\n",
    "    change_amount = predicted_price - current_price\n",
    "    change_percent = (change_amount / current_price) * 100\n",
    "    signal = generate_signal(change_percent)\n",
    "    recommendations = generate_recommendations(request.commodity, signal, change_percent)\n",
    "    current_date = datetime.now()\n",
    "    forecast_date = current_date + timedelta(days=request.forecast_days)\n",
    "\n",
    "    return {\n",
    "        'commodity': request.commodity,\n",
    "        'current_price': round(current_price, 2),\n",
    "        'current_date': current_date.strftime('%Y-%m-%d'),\n",
    "        'forecast_date': forecast_date.strftime('%Y-%m-%d'),\n",
    "        'predicted_price': round(predicted_price, 2),\n",
    "        'change_amount': round(change_amount, 2),\n",
    "        'change_percent': round(change_percent, 2),\n",
    "        'signal': signal,\n",
    "        'confidence': 0.85,\n",
    "        'recommendations': recommendations\n",
    "    }\n",
    "\n",
    "@app.get('/dashboard', response_model=DashboardResponse)\n",
    "def get_dashboard():\n",
    "    commodities_data = []\n",
    "    for commodity_id in models.keys():\n",
    "        try:\n",
    "            current_price = get_current_price(commodity_id)\n",
    "            features = get_latest_features(commodity_id)\n",
    "            predicted_price = models[commodity_id].predict(features)[0]\n",
    "            change_amount = predicted_price - current_price\n",
    "            change_percent = (change_amount / current_price) * 100\n",
    "            signal = generate_signal(change_percent)\n",
    "            commodities_data.append({\n",
    "                'id': commodity_id,\n",
    "                'name': commodity_info[commodity_id]['name'],\n",
    "                'current_price': round(current_price, 2),\n",
    "                'predicted_price_30d': round(predicted_price, 2),\n",
    "                'change_percent_30d': round(change_percent, 2),\n",
    "                'signal': signal,\n",
    "                'unit': commodity_info[commodity_id]['unit'],\n",
    "                'currency': commodity_info[commodity_id]['currency']\n",
    "            })\n",
    "        except Exception as e:\n",
    "            print(f\"Error processing {commodity_id}: {e}\")\n",
    "            continue\n",
    "    return {'commodities': commodities_data}\n",
    "\n",
    "@app.get('/health')\n",
    "def health_check():\n",
    "    return {'status': 'healthy', 'models_loaded': len(models)}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "a7ee2e46-2150-48b1-919a-7648a1830052",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
