{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a7144036-a8a9-4840-92fd-b333fb5993cd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: fastapi in c:\\users\\tumel\\anaconda3\\lib\\site-packages (0.129.0)\n",
      "Requirement already satisfied: uvicorn in c:\\users\\tumel\\anaconda3\\lib\\site-packages (0.41.0)\n",
      "Requirement already satisfied: starlette<1.0.0,>=0.40.0 in c:\\users\\tumel\\anaconda3\\lib\\site-packages (from fastapi) (0.52.1)\n",
      "Requirement already satisfied: pydantic>=2.7.0 in c:\\users\\tumel\\anaconda3\\lib\\site-packages (from fastapi) (2.12.5)\n",
      "Requirement already satisfied: typing-extensions>=4.8.0 in c:\\users\\tumel\\anaconda3\\lib\\site-packages (from fastapi) (4.15.0)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in c:\\users\\tumel\\anaconda3\\lib\\site-packages (from fastapi) (0.4.2)\n",
      "Requirement already satisfied: annotated-doc>=0.0.2 in c:\\users\\tumel\\anaconda3\\lib\\site-packages (from fastapi) (0.0.4)\n",
      "Requirement already satisfied: click>=7.0 in c:\\users\\tumel\\anaconda3\\lib\\site-packages (from uvicorn) (8.1.7)\n",
      "Requirement already satisfied: h11>=0.8 in c:\\users\\tumel\\anaconda3\\lib\\site-packages (from uvicorn) (0.16.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\tumel\\anaconda3\\lib\\site-packages (from click>=7.0->uvicorn) (0.4.6)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in c:\\users\\tumel\\anaconda3\\lib\\site-packages (from pydantic>=2.7.0->fastapi) (0.7.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.5 in c:\\users\\tumel\\anaconda3\\lib\\site-packages (from pydantic>=2.7.0->fastapi) (2.41.5)\n",
      "Requirement already satisfied: anyio<5,>=3.6.2 in c:\\users\\tumel\\anaconda3\\lib\\site-packages (from starlette<1.0.0,>=0.40.0->fastapi) (4.2.0)\n",
      "Requirement already satisfied: idna>=2.8 in c:\\users\\tumel\\anaconda3\\lib\\site-packages (from anyio<5,>=3.6.2->starlette<1.0.0,>=0.40.0->fastapi) (3.4)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\users\\tumel\\anaconda3\\lib\\site-packages (from anyio<5,>=3.6.2->starlette<1.0.0,>=0.40.0->fastapi) (1.3.0)\n"
     ]
    }
   ],
   "source": [
    "\n",
    "!pip install fastapi uvicorn\n",
    "from fastapi import FastAPI, HTTPException\n",
    "from fastapi.middleware.cors import CORSMiddleware\n",
    "from pydantic import BaseModel\n",
    "import joblib\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "app = FastAPI(title=\"CommodityIQ API\")\n",
    "\n",
    "# CORS for Lovable frontend\n",
    "app.add_middleware(\n",
    "    CORSMiddleware,\n",
    "    allow_origins=['*'],\n",
    "    allow_methods=['*'],\n",
    "    allow_headers=['*']\n",
    ")\n",
    "\n",
    "# ============================================\n",
    "# LOAD ALL MODELS AT STARTUP\n",
    "# ============================================\n",
    "\n",
    "models = {\n",
    "    'gold': joblib.load('gold_xgb_model.pkl'),\n",
    "    'platinum': joblib.load('platinum_xgb_model.pkl'),\n",
    "    'oil': joblib.load('oil_xgb_model.pkl'),\n",
    "    'copper': joblib.load('copper_xgb_model.pkl'),\n",
    "}\n",
    "\n",
    "# Commodity metadata\n",
    "commodity_info = {\n",
    "    'gold': {\n",
    "        'name': 'Gold',\n",
    "        'unit': 'oz',\n",
    "        'currency': 'USD',\n",
    "    },\n",
    "    'platinum': {\n",
    "        'name': 'Platinum',\n",
    "        'unit': 'oz',\n",
    "        'currency': 'USD',\n",
    "    },\n",
    "    'oil': {\n",
    "        'name': 'Crude Oil',\n",
    "        'unit': 'barrel',\n",
    "        'currency': 'USD',\n",
    "    },\n",
    "    'copper': {\n",
    "        'name': 'Copper',\n",
    "        'unit': 'lb',\n",
    "        'currency': 'USD',\n",
    "    },\n",
    "}\n",
    "\n",
    "# ============================================\n",
    "# PYDANTIC MODELS\n",
    "# ============================================\n",
    "\n",
    "class PredictionRequest(BaseModel):\n",
    "    commodity: str\n",
    "    forecast_days: int = 30\n",
    "\n",
    "class PredictionResponse(BaseModel):\n",
    "    commodity: str\n",
    "    current_price: float\n",
    "    current_date: str\n",
    "    forecast_date: str\n",
    "    predicted_price: float\n",
    "    change_amount: float\n",
    "    change_percent: float\n",
    "    signal: str\n",
    "    confidence: float\n",
    "    recommendations: list\n",
    "\n",
    "class DashboardResponse(BaseModel):\n",
    "    commodities: list\n",
    "\n",
    "# ============================================\n",
    "# HELPER FUNCTIONS\n",
    "# ============================================\n",
    "\n",
    "def get_current_price(commodity: str) -> float:\n",
    "    sample_prices = {\n",
    "        'gold': 3000,\n",
    "        'platinum': 980,\n",
    "        'oil': 85.50,\n",
    "        'copper': 4.50\n",
    "    }\n",
    "    return sample_prices.get(commodity, 0)\n",
    "\n",
    "def get_latest_features(commodity: str) -> pd.DataFrame:\n",
    "    if commodity == 'gold':\n",
    "        features = pd.DataFrame({\n",
    "            'gold_price': [3000],\n",
    "            'gold_ma_7': [2980],\n",
    "            'gold_ma_30': [2950],\n",
    "            'gold_ma_200': [2800],\n",
    "            'gold_volatility': [50],\n",
    "            'gold_roc': [0.02],\n",
    "            'usd_zar': [18.5],\n",
    "            'usd_zar_ma_30': [18.3],\n",
    "            'usd_zar_change': [0.01],\n",
    "            'rsi': [62],\n",
    "            'month': [datetime.now().month],\n",
    "            'quarter': [datetime.now().quarter]\n",
    "        })\n",
    "    elif commodity == 'platinum':\n",
    "        features = pd.DataFrame({\n",
    "            'platinum_price': [980],\n",
    "            'platinum_ma_7': [975],\n",
    "            'platinum_ma_30': [965],\n",
    "            'platinum_ma_200': [940],\n",
    "            'platinum_volatility': [20],\n",
    "            'platinum_roc': [0.015],\n",
    "            'usd_zar': [18.5],\n",
    "            'usd_zar_ma_30': [18.3],\n",
    "            'usd_zar_change': [0.01],\n",
    "            'rsi': [55],\n",
    "            'month': [datetime.now().month],\n",
    "            'quarter': [datetime.now().quarter]\n",
    "        })\n",
    "    elif commodity == 'oil':\n",
    "        features = pd.DataFrame({\n",
    "            'oil_price': [85.50],\n",
    "            'oil_ma_7': [85.00],\n",
    "            'oil_ma_30': [84.50],\n",
    "            'oil_ma_200': [82.00],\n",
    "            'oil_volatility': [5.2],\n",
    "            'oil_roc': [0.015],\n",
    "            'usd_zar': [18.5],\n",
    "            'usd_zar_ma_30': [18.3],\n",
    "            'usd_zar_change': [0.005],\n",
    "            'rsi': [58],\n",
    "            'month': [datetime.now().month],\n",
    "            'quarter': [datetime.now().quarter]\n",
    "        })\n",
    "    elif commodity == 'copper':\n",
    "        features = pd.DataFrame({\n",
    "            'copper_price': [4.50],\n",
    "            'copper_ma_7': [4.48],\n",
    "            'copper_ma_30': [4.42],\n",
    "            'copper_ma_200': [4.20],\n",
    "            'copper_volatility': [0.15],\n",
    "            'copper_roc': [0.012],\n",
    "            'usd_zar': [18.5],\n",
    "            'usd_zar_ma_30': [18.3],\n",
    "            'usd_zar_change': [0.01],\n",
    "            'rsi': [60],\n",
    "            'month': [datetime.now().month],\n",
    "            'quarter': [datetime.now().quarter]\n",
    "        })\n",
    "    return features\n",
    "\n",
    "def generate_signal(change_percent: float) -> str:\n",
    "    if change_percent > 5:\n",
    "        return \"STRONG BUY\"\n",
    "    elif change_percent > 2:\n",
    "        return \"BUY\"\n",
    "    elif change_percent < -5:\n",
    "        return \"STRONG SELL\"\n",
    "    elif change_percent < -2:\n",
    "        return \"SELL\"\n",
    "    else:\n",
    "        return \"HOLD\"\n",
    "\n",
    "def generate_recommendations(commodity: str, signal: str, change_percent: float) -> list:\n",
    "    if commodity in ['gold', 'platinum']:\n",
    "        if signal in ['BUY', 'STRONG BUY']:\n",
    "            return [\n",
    "                \"Increase production immediately\",\n",
    "                f\"Expect {abs(change_percent):.1f}% price increase\",\n",
    "                \"Consider stockpiling refined metal\",\n",
    "                \"Hedge 50% of next quarter production\"\n",
    "            ]\n",
    "        elif signal in ['SELL', 'STRONG SELL']:\n",
    "            return [\n",
    "                \"Sell current stockpile NOW\",\n",
    "                f\"Prices may drop {abs(change_percent):.1f}%\",\n",
    "                \"Reduce production temporarily\",\n",
    "                \"Wait for market recovery\"\n",
    "            ]\n",
    "        else:\n",
    "            return [\n",
    "                \"Maintain current production levels\",\n",
    "                \"Market is stable - no urgent action\",\n",
    "                \"Monitor closely for changes\"\n",
    "            ]\n",
    "    elif commodity == 'oil':\n",
    "        if signal in ['BUY', 'STRONG BUY']:\n",
    "            return [\n",
    "                \"HEDGE fuel costs immediately!\",\n",
    "                f\"Oil may rise {abs(change_percent):.1f}%\",\n",
    "                \"Lock in current fuel contracts\",\n",
    "                \"Consider passing costs to customers\"\n",
    "            ]\n",
    "        elif signal in ['SELL', 'STRONG SELL']:\n",
    "            return [\n",
    "                \"DO NOT HEDGE - wait for lower prices\",\n",
    "                f\"Oil costs may drop {abs(change_percent):.1f}%\",\n",
    "                \"Delay large fuel purchases\",\n",
    "                \"Use spot market instead of contracts\"\n",
    "            ]\n",
    "        else:\n",
    "            return [\n",
    "                \"Normal purchasing patterns\",\n",
    "                \"Oil prices stable\",\n",
    "                \"No urgent hedging needed\"\n",
    "            ]\n",
    "    elif commodity == 'copper':\n",
    "        if signal in ['BUY', 'STRONG BUY']:\n",
    "            return [\n",
    "                \"Purchase copper NOW before price rise\",\n",
    "                f\"Prices rising {abs(change_percent):.1f}%\",\n",
    "                \"Lock in 6-month supply contracts\",\n",
    "                \"Start copper-intensive projects earlier\"\n",
    "            ]\n",
    "        elif signal in ['SELL', 'STRONG SELL']:\n",
    "            return [\n",
    "                \"WAIT to purchase copper\",\n",
    "                f\"Prices dropping {abs(change_percent):.1f}%\",\n",
    "                \"Delay non-urgent purchases\",\n",
    "                \"Negotiate lower prices with suppliers\"\n",
    "            ]\n",
    "        else:\n",
    "            return [\n",
    "                \"Normal purchasing patterns\",\n",
    "                \"Copper prices stable\",\n",
    "                \"No urgency\"\n",
    "            ]\n",
    "    return []\n",
    "\n",
    "# ============================================\n",
    "# API ENDPOINTS\n",
    "# ============================================\n",
    "\n",
    "@app.get('/')\n",
    "def home():\n",
    "    return {\n",
    "        'name': 'CommodityIQ API',\n",
    "        'version': '1.0.0',\n",
    "        'status': 'running',\n",
    "        'available_commodities': list(models.keys())\n",
    "    }\n",
    "\n",
    "@app.get('/commodities')\n",
    "def list_commodities():\n",
    "    return {\n",
    "        'commodities': [\n",
    "            {\n",
    "                'id': key,\n",
    "                'name': info['name'],\n",
    "                'unit': info['unit'],\n",
    "                'currency': info['currency']\n",
    "            }\n",
    "            for key, info in commodity_info.items()\n",
    "        ]\n",
    "    }\n",
    "\n",
    "@app.post('/predict', response_model=PredictionResponse)\n",
    "def predict(request: PredictionRequest):\n",
    "    if request.commodity not in models:\n",
    "        raise HTTPException(\n",
    "            status_code=400,\n",
    "            detail=f\"Commodity '{request.commodity}' not supported. Available: {list(models.keys())}\"\n",
    "        )\n",
    "    if request.forecast_days not in [7, 30, 60, 90]:\n",
    "        raise HTTPException(\n",
    "            status_code=400,\n",
    "            detail=\"forecast_days must be 7, 30, 60, or 90\"\n",
    "        )\n",
    "\n",
    "    current_price = get_current_price(request.commodity)\n",
    "    features = get_latest_features(request.commodity)\n",
    "    model = models[request.commodity]\n",
    "    predicted_price = model.predict(features)[0]\n",
    "\n",
    "    if request.forecast_days == 7:\n",
    "        predicted_price = current_price + (predicted_price - current_price) * 0.25\n",
    "    elif request.forecast_days == 60:\n",
    "        predicted_price = current_price + (predicted_price - current_price) * 1.8\n",
    "    elif request.forecast_days == 90:\n",
    "        predicted_price = current_price + (predicted_price - current_price) * 2.5\n",
    "\n",
    "    change_amount = predicted_price - current_price\n",
    "    change_percent = (change_amount / current_price) * 100\n",
    "    signal = generate_signal(change_percent)\n",
    "    recommendations = generate_recommendations(request.commodity, signal, change_percent)\n",
    "\n",
    "    current_date = datetime.now()\n",
    "    forecast_date = current_date + timedelta(days=request.forecast_days)\n",
    "\n",
    "    return {\n",
    "        'commodity': request.commodity,\n",
    "        'current_price': round(current_price, 2),\n",
    "        'current_date': current_date.strftime('%Y-%m-%d'),\n",
    "        'forecast_date': forecast_date.strftime('%Y-%m-%d'),\n",
    "        'predicted_price': round(predicted_price, 2),\n",
    "        'change_amount': round(change_amount, 2),\n",
    "        'change_percent': round(change_percent, 2),\n",
    "        'signal': signal,\n",
    "        'confidence': 0.85,\n",
    "        'recommendations': recommendations\n",
    "    }\n",
    "\n",
    "@app.get('/dashboard', response_model=DashboardResponse)\n",
    "def get_dashboard():\n",
    "    commodities_data = []\n",
    "    for commodity_id in models.keys():\n",
    "        try:\n",
    "            current_price = get_current_price(commodity_id)\n",
    "            features = get_latest_features(commodity_id)\n",
    "            model = models[commodity_id]\n",
    "            predicted_price = model.predict(features)[0]\n",
    "\n",
    "            change_amount = predicted_price - current_price\n",
    "            change_percent = (change_amount / current_price) * 100\n",
    "            signal = generate_signal(change_percent)\n",
    "\n",
    "            commodities_data.append({\n",
    "                'id': commodity_id,\n",
    "                'name': commodity_info[commodity_id]['name'],\n",
    "                'current_price': round(current_price, 2),\n",
    "                'predicted_price_30d': round(predicted_price, 2),\n",
    "                'change_percent_30d': round(change_percent, 2),\n",
    "                'signal': signal,\n",
    "                'unit': commodity_info[commodity_id]['unit'],\n",
    "                'currency': commodity_info[commodity_id]['currency']\n",
    "            })\n",
    "        except Exception as e:\n",
    "            print(f\"Error processing {commodity_id}: {e}\")\n",
    "            continue\n",
    "\n",
    "    return {'commodities': commodities_data}\n",
    "\n",
    "@app.get('/health')\n",
    "def health_check():\n",
    "    return {'status': 'healthy', 'models_loaded': len(models)}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "08391663-db69-4c54-9aa3-f4070d4d49d3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Save the API code to a file\n",
    "import subprocess"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "0a25aae1-a6ec-4c74-9ea6-e639c4d5300e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: nest_asyncio in c:\\users\\tumel\\anaconda3\\lib\\site-packages (1.6.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install nest_asyncio"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": none,
   "id": "9502adb9-0850-4117-b68b-4d6c4d51c18b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:     Started server process [15500]\n",
      "INFO:     Waiting for application startup.\n",
      "INFO:     Application startup complete.\n",
      "INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:     127.0.0.1:54829 - \"GET /docs HTTP/1.1\" 200 OK\n",
      "INFO:     127.0.0.1:51918 - \"GET /openapi.json HTTP/1.1\" 200 OK\n"
     ]
    }
   ],
   "source": [
    "import asyncio\n",
    "import uvicorn\n",
    "\n",
    "config = uvicorn.Config(app, host=\"0.0.0.0\", port=8000)\n",
    "server = uvicorn.Server(config)\n",
    "await server.serve()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d8a9fb67-bbda-4d11-972d-db4d05091bc8",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
